
export const MAIN_SLIDER_POSITION = "MAIN_SLIDER_POSITION"
export const MAIN_SLIDER_SCREENS ="MAIN_SLIDER_SCREENS"
export const FETCH_TRACKS_SUCCESS = "FETCH_TRACKS_SUCCESS"
export const SET_POSITION_MAIN_SLIDER = "SET_POSITION_MAIN_SLIDER"
export const SET_SHOW_CASE_FROM_SETVER = "SET_SHOW_CASE_FROM_SETVER"
export const SET_APARTMENT_TO_STATE = "SET_APARTMENT_TO_STATE" 
export const SET_SELECTED_ROOM_ON_FOCUS = "SET_SHOW_CASE_ON_FOCUS"
export const SET_INDEX_OF_SELECTED_ROOM = "SET_INDEX_OF_SELECTED_ROOM" 
export const SET_SYMBOL_FOR_CACL = "SET_SYMBOL_FOR_CACL"
export const SET_MORTGEGE_LENGTH = "SET_MORTGEGE_LENGTH"
export const SET_INDEX_OF_SELECTED_APARTMENT = "SET_INDEX_OF_SELECTED_APARTMENT"
export const SET_SHOWCASE_BOOLEAN_ANIMATION = "SET_SHOWCASE_BOOLEAN_ANIMATION"
export const SET_APARTMENTS_FROM_SERVER = "SET_APARTMENTS_FROM_SERVER"
export const SET_CART_COMPANY_EMPLOYEES_POSITION = "SET_CART_COMPANY_EMPLOYEES_POSITION"
export const SET_COMPANY_EMPLOYEES = "SET_COMPANY_EMPLOYEES"
export const SET_PICTURES_OF_COMPANY_EMPLOYEES = "SET_PICTURES_OF_COMPANY_EMPLOYEES"
export const SET_INFORMATION_EMPLOYEES = "SET_INFORMATION_EMPLOYEES"
export const SET_POSITION_PICTURE_OF_ROOM = "SET_POSITION_PICTURE_OF_ROOM"
export const SET_INTERVAL_FOR_PICTURE = "SET_INTERVAL_FOR_PICTURE"
export const SET_POSITION_OF_PICTURE = "SET_POSITION_OF_PICTURE"
export const SET_INTERVAL_ID_FOR_PICTURE = "SET_INTERVAL_ID_FOR_PICTURE"
export const SET_MONTHLY_PAYMENT = "SET_MONTHLY_PAYMENT"
export const SET_POSITION_PUCTURE_HOUSE_ITSELF = "SET_POSITION_PUCTURE_HOUSE_ITSELF"
export const SET_INTERVAL_ID_PICTURE_HOUSE_ITSELF = "SET_INTERVAL_ID_PICTURE_HOUSE_ITSELF"
export const SET_POSITION_OF_ALL_COMPONENTS = "SET_POSITION_OF_ALL_COMPONENTS"





